#Asking Page
#TF
import streamlit as st
import sqlite3
import backend
from backend import get_schema_text, generate_sql, is_safe, run_query
 
icon, title = st.columns([0.03, 0.97], vertical_alignment="center", gap="small")
with icon:
    st.image("assets/icons/bot.svg", width=35)
with title:
    st.title("Ask Your Data")
 
 
#Question
default_question = st.session_state.get("default_question", "")
 
with st.container(border=True):
 
    icon, title = st.columns([0.03, 0.97], vertical_alignment="center", gap="small")
    with icon:
        st.image("assets/icons/message-circle.svg", width=28)
    with title:
        st.subheader("Ask a Question")
 
    input_col, button_col = st.columns([6, 1])
 
    with input_col:
 
        question = st.text_input(
            "Question",
            value=default_question,
            placeholder="e.g. Which company has the most active buses?",
            label_visibility="collapsed",
        )
 
    with button_col:
 
        ask_clicked = st.button(
            "Ask",
            type="primary",
            use_container_width=True,
        )
 
with st.container(border=True):

    icon, title = st.columns([0.03, 0.97], vertical_alignment="center", gap="small")

    with icon:
        st.image("assets/icons/square-arrow-right-exit.svg", width=28)

    with title:
        st.subheader("Choose Output")

    st.caption(
        "Select one or more output formats for your answer."
    )

    sql_checkbox, chart_checkbox, table_checkbox = st.columns(3)#LK

    with sql_checkbox:
        with st.container(border=True):

            st.image("assets/icons/database-search.svg", width=36)

            st.markdown("**SQL Query**")

            st.caption(
                "View the SQL statement generated by the AI."
            )

            sql = st.checkbox(
                "Select SQL Query",
                label_visibility="collapsed"
            )

    with chart_checkbox:
        with st.container(border=True):

            st.image("assets/icons/chart-no-axes-combined.svg", width=36)

            st.markdown("**Chart**")

            st.caption(
                "Visualise your results whenever possible."
            )

            chart = st.checkbox(
                "Select Chart",
                label_visibility="collapsed"
            )

    with table_checkbox:
        with st.container(border=True):

            st.image("assets/icons/rows-3.svg", width=36)

            st.markdown("**Results Table**")

            st.caption(
                "Display the returned records in a table."
            )

            table_option = st.checkbox(
                "Select Results Table",
                label_visibility="collapsed"
            )
 
#Save Selected Outputs
selected_outputs = []
 
if sql:
    selected_outputs.append("sql")
if chart:
    selected_outputs.append("chart")
if table_option:
    selected_outputs.append("table")
 
 
#TF
#Ask Button
if ask_clicked:
 
    if not question.strip():
        st.warning("Please enter a question.")
 
    elif len(selected_outputs) == 0:
        st.warning("Please select at least one output type.")
 
    else:
        try:
            with st.spinner("Generating and running your query..."):
 
                schema = get_schema_text() #LF
                generated_sql = generate_sql(question, schema)
 
                if not backend.is_safe(generated_sql):
                    st.error("The generated query was rejected for safety.")
                    st.stop()
 
                
                results = backend.run_query(generated_sql)

                related_sql = backend.generate_related_sql(question,generated_sql,schema,)

                if not backend.is_safe(related_sql):
                    st.error("The related query was rejected for safety.")
                    st.stop()

                related_results = backend.run_query(related_sql)
                
                st.session_state.question = question
                st.session_state.outputs = selected_outputs
                st.session_state.generated_sql = generated_sql
                st.session_state.results = results
                st.session_state.related_sql = related_sql#LK
                st.session_state.related_results = related_results#LK
 
                st.switch_page("pages/Results.py")
 
        except sqlite3.Error as error:
            st.error(f"Database error: {error}")
 
        except Exception as error:
            st.error(f"Unable to generate the answer: {error}")
#LK